AllCops:
  TargetRubyVersion: 2.7.0

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Max: 100

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8